name = "MatrixEquationsAD"
uuid = "283a1a7b-c18a-432b-b100-bdc256e73a32"
authors = ["Jesse Perla <jesseperla@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
